// Generated by `npm run db:types` — do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      app_config: {
        Row: {
          description: string
          key: string
          updated_at: string
          updated_by: string | null
          value: Json
        }
        Insert: {
          description: string
          key: string
          updated_at?: string
          updated_by?: string | null
          value: Json
        }
        Update: {
          description?: string
          key?: string
          updated_at?: string
          updated_by?: string | null
          value?: Json
        }
        Relationships: [
          {
            foreignKeyName: "app_config_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "app_config_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      blocks: {
        Row: {
          blocked_id: string
          blocker_id: string
          created_at: string
        }
        Insert: {
          blocked_id: string
          blocker_id: string
          created_at?: string
        }
        Update: {
          blocked_id?: string
          blocker_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "blocks_blocked_id_fkey"
            columns: ["blocked_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "blocks_blocked_id_fkey"
            columns: ["blocked_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "blocks_blocker_id_fkey"
            columns: ["blocker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "blocks_blocker_id_fkey"
            columns: ["blocker_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      conversation_members: {
        Row: {
          conversation_id: string
          last_read_at: string
          profile_id: string
        }
        Insert: {
          conversation_id: string
          last_read_at?: string
          profile_id: string
        }
        Update: {
          conversation_id?: string
          last_read_at?: string
          profile_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "conversation_members_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversation_list"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversation_members_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversation_members_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversation_members_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      conversations: {
        Row: {
          created_at: string
          direct_higher_id: string | null
          direct_lower_id: string | null
          id: string
          plan_id: string | null
        }
        Insert: {
          created_at?: string
          direct_higher_id?: string | null
          direct_lower_id?: string | null
          id?: string
          plan_id?: string | null
        }
        Update: {
          created_at?: string
          direct_higher_id?: string | null
          direct_lower_id?: string | null
          id?: string
          plan_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "conversations_direct_higher_id_fkey"
            columns: ["direct_higher_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_direct_higher_id_fkey"
            columns: ["direct_higher_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_direct_lower_id_fkey"
            columns: ["direct_lower_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_direct_lower_id_fkey"
            columns: ["direct_lower_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_plan_id_fkey"
            columns: ["plan_id"]
            isOneToOne: false
            referencedRelation: "plans"
            referencedColumns: ["id"]
          },
        ]
      }
      legal_acceptances: {
        Row: {
          accepted_at: string
          app_version: string | null
          document_id: string
          id: string
          platform: Database["public"]["Enums"]["platform"] | null
          profile_id: string
        }
        Insert: {
          accepted_at?: string
          app_version?: string | null
          document_id: string
          id?: string
          platform?: Database["public"]["Enums"]["platform"] | null
          profile_id: string
        }
        Update: {
          accepted_at?: string
          app_version?: string | null
          document_id?: string
          id?: string
          platform?: Database["public"]["Enums"]["platform"] | null
          profile_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "legal_acceptances_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "legal_documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "legal_acceptances_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "legal_acceptances_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      legal_documents: {
        Row: {
          content_md: string
          effective_at: string
          id: string
          kind: Database["public"]["Enums"]["legal_doc_kind"]
          locale: string
          requires_reacceptance: boolean
          version: string
        }
        Insert: {
          content_md: string
          effective_at: string
          id?: string
          kind: Database["public"]["Enums"]["legal_doc_kind"]
          locale?: string
          requires_reacceptance?: boolean
          version: string
        }
        Update: {
          content_md?: string
          effective_at?: string
          id?: string
          kind?: Database["public"]["Enums"]["legal_doc_kind"]
          locale?: string
          requires_reacceptance?: boolean
          version?: string
        }
        Relationships: []
      }
      messages: {
        Row: {
          author_id: string
          content: string
          conversation_id: string
          created_at: string
          id: string
        }
        Insert: {
          author_id: string
          content: string
          conversation_id: string
          created_at?: string
          id?: string
        }
        Update: {
          author_id?: string
          content?: string
          conversation_id?: string
          created_at?: string
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversation_list"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
        ]
      }
      places: {
        Row: {
          address: string
          created_at: string
          id: string
          name: string
          point: unknown
          profile_id: string | null
          provider_place_id: string | null
        }
        Insert: {
          address: string
          created_at?: string
          id?: string
          name: string
          point: unknown
          profile_id?: string | null
          provider_place_id?: string | null
        }
        Update: {
          address?: string
          created_at?: string
          id?: string
          name?: string
          point?: unknown
          profile_id?: string | null
          provider_place_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "places_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "places_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      plan_members: {
        Row: {
          created_at: string
          is_host: boolean
          left_at: string | null
          message: string | null
          outcome: Database["public"]["Enums"]["attendance_outcome"] | null
          plan_id: string
          profile_id: string
          recorded_at: string | null
          requested_at: string | null
          seated_at: string | null
          status: Database["public"]["Enums"]["member_status"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          is_host?: boolean
          left_at?: string | null
          message?: string | null
          outcome?: Database["public"]["Enums"]["attendance_outcome"] | null
          plan_id: string
          profile_id: string
          recorded_at?: string | null
          requested_at?: string | null
          seated_at?: string | null
          status: Database["public"]["Enums"]["member_status"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          is_host?: boolean
          left_at?: string | null
          message?: string | null
          outcome?: Database["public"]["Enums"]["attendance_outcome"] | null
          plan_id?: string
          profile_id?: string
          recorded_at?: string | null
          requested_at?: string | null
          seated_at?: string | null
          status?: Database["public"]["Enums"]["member_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "plan_members_plan_id_fkey"
            columns: ["plan_id"]
            isOneToOne: false
            referencedRelation: "plans"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "plan_members_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "plan_members_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      plan_series: {
        Row: {
          active: boolean
          created_at: string
          duration_minutes: number | null
          id: string
          join_mode: Database["public"]["Enums"]["join_mode"]
          languages: Database["public"]["Enums"]["language_code"][]
          place_id: string
          repeats_on: number
          seats: number | null
          start_time: string
          title: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          duration_minutes?: number | null
          id?: string
          join_mode?: Database["public"]["Enums"]["join_mode"]
          languages?: Database["public"]["Enums"]["language_code"][]
          place_id: string
          repeats_on: number
          seats?: number | null
          start_time: string
          title: string
        }
        Update: {
          active?: boolean
          created_at?: string
          duration_minutes?: number | null
          id?: string
          join_mode?: Database["public"]["Enums"]["join_mode"]
          languages?: Database["public"]["Enums"]["language_code"][]
          place_id?: string
          repeats_on?: number
          seats?: number | null
          start_time?: string
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "plan_series_place_id_fkey"
            columns: ["place_id"]
            isOneToOne: false
            referencedRelation: "places"
            referencedColumns: ["id"]
          },
        ]
      }
      plans: {
        Row: {
          age_max: number | null
          age_min: number | null
          cancelled_at: string | null
          created_at: string
          duration_minutes: number | null
          host_id: string | null
          id: string
          join_mode: Database["public"]["Enums"]["join_mode"]
          languages: Database["public"]["Enums"]["language_code"][]
          place_id: string
          seats: number | null
          series_id: string | null
          starts_at: string
          title: string
          updated_at: string
        }
        Insert: {
          age_max?: number | null
          age_min?: number | null
          cancelled_at?: string | null
          created_at?: string
          duration_minutes?: number | null
          host_id?: string | null
          id?: string
          join_mode?: Database["public"]["Enums"]["join_mode"]
          languages?: Database["public"]["Enums"]["language_code"][]
          place_id: string
          seats?: number | null
          series_id?: string | null
          starts_at: string
          title: string
          updated_at?: string
        }
        Update: {
          age_max?: number | null
          age_min?: number | null
          cancelled_at?: string | null
          created_at?: string
          duration_minutes?: number | null
          host_id?: string | null
          id?: string
          join_mode?: Database["public"]["Enums"]["join_mode"]
          languages?: Database["public"]["Enums"]["language_code"][]
          place_id?: string
          seats?: number | null
          series_id?: string | null
          starts_at?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "plans_host_id_fkey"
            columns: ["host_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "plans_host_id_fkey"
            columns: ["host_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "plans_place_id_fkey"
            columns: ["place_id"]
            isOneToOne: false
            referencedRelation: "places"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "plans_series_id_fkey"
            columns: ["series_id"]
            isOneToOne: false
            referencedRelation: "plan_series"
            referencedColumns: ["id"]
          },
        ]
      }
      profile_locations: {
        Row: {
          point: unknown
          profile_id: string
          updated_at: string
        }
        Insert: {
          point: unknown
          profile_id: string
          updated_at?: string
        }
        Update: {
          point?: unknown
          profile_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profile_locations_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profile_locations_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: true
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profile_views: {
        Row: {
          profile_id: string
          viewed_at: string
          viewer_id: string
        }
        Insert: {
          profile_id: string
          viewed_at?: string
          viewer_id: string
        }
        Update: {
          profile_id?: string
          viewed_at?: string
          viewer_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "profile_views_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profile_views_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profile_views_viewer_id_fkey"
            columns: ["viewer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profile_views_viewer_id_fkey"
            columns: ["viewer_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          age_max: number
          age_min: number
          app_language: string
          audience_gender: Database["public"]["Enums"]["audience_gender"]
          avatar_storage_path: string | null
          bio: string | null
          birthdate: string | null
          country_code: string | null
          created_at: string
          deleted_at: string | null
          distance_unit: Database["public"]["Enums"]["distance_unit"]
          gender: Database["public"]["Enums"]["gender"] | null
          id: string
          interests: string[]
          languages: Database["public"]["Enums"]["language_code"][]
          name: string
          neighbourhood: string | null
          notifications_enabled: boolean
          onboarding_completed_at: string | null
          pronouns: Database["public"]["Enums"]["pronouns"]
          radius: number
          updated_at: string
        }
        Insert: {
          age_max?: number
          age_min?: number
          app_language?: string
          audience_gender?: Database["public"]["Enums"]["audience_gender"]
          avatar_storage_path?: string | null
          bio?: string | null
          birthdate?: string | null
          country_code?: string | null
          created_at?: string
          deleted_at?: string | null
          distance_unit?: Database["public"]["Enums"]["distance_unit"]
          gender?: Database["public"]["Enums"]["gender"] | null
          id: string
          interests?: string[]
          languages?: Database["public"]["Enums"]["language_code"][]
          name?: string
          neighbourhood?: string | null
          notifications_enabled?: boolean
          onboarding_completed_at?: string | null
          pronouns?: Database["public"]["Enums"]["pronouns"]
          radius?: number
          updated_at?: string
        }
        Update: {
          age_max?: number
          age_min?: number
          app_language?: string
          audience_gender?: Database["public"]["Enums"]["audience_gender"]
          avatar_storage_path?: string | null
          bio?: string | null
          birthdate?: string | null
          country_code?: string | null
          created_at?: string
          deleted_at?: string | null
          distance_unit?: Database["public"]["Enums"]["distance_unit"]
          gender?: Database["public"]["Enums"]["gender"] | null
          id?: string
          interests?: string[]
          languages?: Database["public"]["Enums"]["language_code"][]
          name?: string
          neighbourhood?: string | null
          notifications_enabled?: boolean
          onboarding_completed_at?: string | null
          pronouns?: Database["public"]["Enums"]["pronouns"]
          radius?: number
          updated_at?: string
        }
        Relationships: []
      }
      reports: {
        Row: {
          created_at: string
          detail: string | null
          id: string
          plan_id: string | null
          reason: Database["public"]["Enums"]["report_reason"]
          reporter_id: string | null
          subject_id: string
        }
        Insert: {
          created_at?: string
          detail?: string | null
          id?: string
          plan_id?: string | null
          reason: Database["public"]["Enums"]["report_reason"]
          reporter_id?: string | null
          subject_id: string
        }
        Update: {
          created_at?: string
          detail?: string | null
          id?: string
          plan_id?: string | null
          reason?: Database["public"]["Enums"]["report_reason"]
          reporter_id?: string | null
          subject_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reports_plan_id_fkey"
            columns: ["plan_id"]
            isOneToOne: false
            referencedRelation: "plans"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_subject_id_fkey"
            columns: ["subject_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_subject_id_fkey"
            columns: ["subject_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      verification_submissions: {
        Row: {
          id: string
          outcome: Database["public"]["Enums"]["verification_status"] | null
          profile_id: string
          purged_at: string | null
          reviewed_at: string | null
          storage_path: string
          submitted_at: string
        }
        Insert: {
          id?: string
          outcome?: Database["public"]["Enums"]["verification_status"] | null
          profile_id: string
          purged_at?: string | null
          reviewed_at?: string | null
          storage_path: string
          submitted_at?: string
        }
        Update: {
          id?: string
          outcome?: Database["public"]["Enums"]["verification_status"] | null
          profile_id?: string
          purged_at?: string | null
          reviewed_at?: string | null
          storage_path?: string
          submitted_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "verification_submissions_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "verification_submissions_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "public_profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      conversation_list: {
        Row: {
          id: string | null
          kind: string | null
          last_message_at: string | null
          member_count: number | null
          members: Json | null
          plan_id: string | null
          preview: string | null
          title: string | null
          unread_count: number | null
        }
        Relationships: [
          {
            foreignKeyName: "conversations_plan_id_fkey"
            columns: ["plan_id"]
            isOneToOne: false
            referencedRelation: "plans"
            referencedColumns: ["id"]
          },
        ]
      }
      public_profiles: {
        Row: {
          age: number | null
          avatar_storage_path: string | null
          bio: string | null
          country_code: string | null
          gender: Database["public"]["Enums"]["gender"] | null
          id: string | null
          interests: string[] | null
          joined_at: string | null
          languages: Database["public"]["Enums"]["language_code"][] | null
          name: string | null
          neighbourhood: string | null
          pronouns: Database["public"]["Enums"]["pronouns"] | null
          verified: boolean | null
        }
        Insert: {
          age?: never
          avatar_storage_path?: string | null
          bio?: string | null
          country_code?: string | null
          gender?: Database["public"]["Enums"]["gender"] | null
          id?: string | null
          interests?: string[] | null
          joined_at?: string | null
          languages?: Database["public"]["Enums"]["language_code"][] | null
          name?: string | null
          neighbourhood?: string | null
          pronouns?: Database["public"]["Enums"]["pronouns"] | null
          verified?: never
        }
        Update: {
          age?: never
          avatar_storage_path?: string | null
          bio?: string | null
          country_code?: string | null
          gender?: Database["public"]["Enums"]["gender"] | null
          id?: string | null
          interests?: string[] | null
          joined_at?: string | null
          languages?: Database["public"]["Enums"]["language_code"][] | null
          name?: string | null
          neighbourhood?: string | null
          pronouns?: Database["public"]["Enums"]["pronouns"] | null
          verified?: never
        }
        Relationships: []
      }
    }
    Functions: {
      add_seat: { Args: { plan: string; profile: string }; Returns: undefined }
      attendance_rate_of: { Args: { uid: string }; Returns: number }
      current_legal_document: {
        Args: {
          doc_kind: Database["public"]["Enums"]["legal_doc_kind"]
          want_locale?: string
        }
        Returns: {
          content_md: string
          effective_at: string
          id: string
          kind: Database["public"]["Enums"]["legal_doc_kind"]
          locale: string
          requires_reacceptance: boolean
          version: string
        }
        SetofOptions: {
          from: "*"
          to: "legal_documents"
          isOneToOne: true
          isSetofReturn: false
        }
      }
      delete_my_account: { Args: never; Returns: undefined }
      distance_to: { Args: { place: string }; Returns: number }
      nearby_plans: {
        Args: {
          verified_hosts_only?: boolean
          want_age_max?: number
          want_age_min?: number
          want_language?: string
        }
        Returns: {
          age_max: number
          age_min: number
          distance_m: number
          duration_minutes: number
          host: Json
          id: string
          join_mode: Database["public"]["Enums"]["join_mode"]
          languages: string[]
          membership: string
          participants: Json
          place: Json
          requests: Json
          seats: number
          series_id: string
          starts_at: string
          title: string
        }[]
      }
      open_direct_conversation: { Args: { other: string }; Returns: string }
      profile_view_count: { Args: { days?: number }; Returns: number }
      profile_viewers: {
        Args: { days?: number }
        Returns: {
          viewed_at: string
          viewer: Json
        }[]
      }
      record_attendance: {
        Args: { absentees?: string[]; plan: string }
        Returns: number
      }
      record_profile_view: { Args: { profile: string }; Returns: undefined }
    }
    Enums: {
      attendance_outcome: "attended" | "cancelled" | "no_show"
      audience_gender: "everyone" | "women" | "men" | "non_binary"
      distance_unit: "mi" | "km"
      gender: "woman" | "man" | "non_binary"
      join_mode: "open" | "approval"
      language_code:
        | "ar"
        | "da"
        | "de"
        | "el"
        | "en"
        | "es"
        | "fr"
        | "he"
        | "hi"
        | "it"
        | "ja"
        | "ko"
        | "nl"
        | "pl"
        | "pt"
        | "ru"
        | "sv"
        | "tr"
        | "uk"
        | "zh"
        | "pt-BR"
      legal_doc_kind: "terms" | "privacy"
      member_status: "requested" | "declined" | "seated" | "left"
      platform: "ios" | "android"
      pronouns: "she" | "he" | "they" | "unspecified"
      report_reason:
        | "harassment"
        | "no_show"
        | "fake_profile"
        | "inappropriate"
        | "other"
      verification_status: "none" | "pending" | "verified" | "rejected"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      attendance_outcome: ["attended", "cancelled", "no_show"],
      audience_gender: ["everyone", "women", "men", "non_binary"],
      distance_unit: ["mi", "km"],
      gender: ["woman", "man", "non_binary"],
      join_mode: ["open", "approval"],
      language_code: [
        "ar",
        "da",
        "de",
        "el",
        "en",
        "es",
        "fr",
        "he",
        "hi",
        "it",
        "ja",
        "ko",
        "nl",
        "pl",
        "pt",
        "ru",
        "sv",
        "tr",
        "uk",
        "zh",
        "pt-BR",
      ],
      legal_doc_kind: ["terms", "privacy"],
      member_status: ["requested", "declined", "seated", "left"],
      platform: ["ios", "android"],
      pronouns: ["she", "he", "they", "unspecified"],
      report_reason: [
        "harassment",
        "no_show",
        "fake_profile",
        "inappropriate",
        "other",
      ],
      verification_status: ["none", "pending", "verified", "rejected"],
    },
  },
} as const
